# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/MultiDiffSeg',
                'doc_host': 'https://Jorgvt.github.io',
                'git_url': 'https://github.com/Jorgvt/MultiDiffSeg',
                'lib_path': 'MultiDiffSeg'},
  'syms': {}}
